"""
Django settings for LaptopStore project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LaptopStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.store_settings_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'LaptopStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# ==========================================
# إعدادات واجهة لوحة التحكم (Jazzmin - UI/UX)
# ==========================================

JAZZMIN_SETTINGS = {
    "site_title": "TechStore Admin",
    "site_header": "TechStore",
    "site_brand": "لوحة تحكم المتجر",
    "welcome_sign": "مرحباً بك يا عمر في نظام إدارة اللابتوبات",
    "copyright": "TechStore SaaS © 2026",
    
    # إخفاء التطبيقات التي لا يحتاجها البائع لتبدو اللوحة نظيفة
    "hide_apps": ["auth", "contenttypes", "sessions", "admin"],
    
    # تخصيص أيقونات القائمة الجانبية (احترافية)
    "icons": {
        "products.Order": "fas fa-shopping-cart",   # أيقونة عربة للطلبات
        "products.Product": "fas fa-laptop",        # أيقونة لابتوب للمنتجات
        "products.Category": "fas fa-tags",         # أيقونة تصنيفات
        "products.StoreSetting": "fas fa-cogs",     # أيقونة ترس للإعدادات
    },
    
    # ترتيب ظهور الأقسام في القائمة الجانبية
    "order_with_respect_to": ["products.Order", "products.Product", "products.Category", "products.StoreSetting"],
    
    # تحسين شكل شاشة إضافة منتج (تفعيل تقسيم البطاقات الذي برمجته أنت)
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    # المظهر الأسود والذهبي الفخم (Black & Gold Premium)
    "navbar": "navbar-dark",
    "theme": "cyborg", # المظهر الداكن الأساسي
    "sidebar": "sidebar-dark-warning", # قائمة جانبية سوداء مع تحديدات ذهبية
    "sidebar_nav_child_indent": True,
    "theme_color": "warning", # جعل الأزرار الأساسية باللون الذهبي
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-warning", # الأزرار المهمة (مثل الحفظ) ذهبية
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}